### ISSUE TITLE
fix: update lineage classifications path

### ISSUE THREAD

**Issue by edenian-prince** [genomicepi/nwss#1]
The lineage classifications repo has changed and is now here: https://github.com/NW-PaGe/lineage_classifications 

I believe this line needs to be changed to account for the new dataset in the new repo:

https://github.com/genomicepi/nwss/blob/43822a313c69d488de1bf2766f599efdbe695a1e/nwss.R#L20

so the new line will be 

`lineages <- read_csv("https://raw.githubusercontent.com/NW-PaGe/lineage_classifications/refs/heads/main/data/lineage_classifications.csv")`

**Comment by genomicepi** [comment]
Updated, thanks so much for reporting!
